apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: blcksrequests
    context: build/blcksrequests
    docker:
      noCache: true
deploy:
  kustomize:
    path: github.com/pnetwork/pnbase//blcksrequests/?ref=master